import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { NameInputMain } from '@/Customer/NameInput/NameInputMain'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const router = useRouter()

    const onEnterName = (name) => {
        router.replace('/menucategories')
    }

    return (<>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <NameInputMain onClick={onEnterName}/>
        </main>
    </>)
}
/**
console.log(" ")
console.log("Home")
console.log(": ", )
*/
