import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// import { Component } from '@/components/Component/Component'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { getQRRequest } from './api/requests'
import {useState, useEffect} from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const router = useRouter()
    const [qrImage, setQRImage] = useState(null);

    // const getQR = async () => {
    //     console.log("getQR")
    //     const response = await getQRRequest()
    //     console.log("response: ", response)
    //     setQRImage(response.data);
    //     // console.log('Placing your order')
    //     // router.push('/product')
    // }


    useEffect(() => {
        if (router.asPath === '/admin') {
            router.replace('/admin');
        }

        
    }, []);


    return (<>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <div className={styles.description}>
                <h1>Welcome Home</h1>
                <Link href='/qrgenerator'>
                    Generar QR
                </Link>

  
                {/* <button onClick={getQR}>Generar QR</button> */}
            </div>
        </main>
    </>)
}
/**
console.log(" ")
console.log("Home")
console.log(": ", )
*/
