import Head from 'next/head'
import {useState, useEffect} from 'react';
import { useRouter } from 'next/router'
import { NameInputMain } from '@/Customer/NameInput/NameInputMain'
import { postCustomer } from '@/requests'
import {MessageDialog} from '@/Common/MessageDialog'
import { useSearchParams} from 'next/navigation'
import {deleteCookie, getCookie, hasCookie, setCookie} from "cookies-next";
import { getTableOrders, tableExistsByTableCode } from '@/requests';

export default function startPage() {
    const router = useRouter()
    const [openRepeatedNameDialog, setOpenRepeatedNameDialog] = useState(false)
    const [openEmptyNameDialog, setOpenEmptyNameDialog] = useState(false)
    const searchParams = useSearchParams()
    const [tableCode, setTableCode] = useState('')
    const [customerName, setCustomerName] = useState('')

    useEffect(() => {
        console.log(' ')
        console.log('Start useEffect')
        initialize()
    }, [])

    const goToBase = () => {
        router.replace({pathname:"/"})
    }

    const initialize = async () => {
        console.log(' ')
        console.log('Home initialize')
        let hasTableCodeCookie = hasCookie("tableCode")
        console.log('hasTableCodeCookie: ', hasTableCodeCookie)

        if(hasTableCodeCookie){
            let tableCode = getCookie("tableCode")
            console.log('tableCode: ', tableCode)
            if(tableCode !== ''){
                setTableCode(tableCode)
                return true
            } 
        }
        goToBase()
    }

    const goToCategories = () => {
        router.replace({
            pathname: "/menucategories",
        })
    }

    const onEnterName = async (name) => {
        console.log(' ')
        console.log('Start onEnterName(name)')
        console.log('name: ', name)
        if(name === ''){
            setOpenEmptyNameDialog(true)
        } else {
            const result = await postCustomer(name, tableCode)
            console.log('result: ', result)
            if(result === 'table-not-exists'){
                setCookie('tableCode', '', {maxAge:60*60*5})
                goToBase()
            } else if(result === 'customer-exists'){
                let hasCustomerNameCookie = hasCookie('customerName')
                console.log('hasCustomerNameCookie: ', hasCustomerNameCookie)
                if(hasCustomerNameCookie){
                    let customerName = getCookie('customerName')
                    if(customerName === name){
                        goToCategories()
                    } else {
                        setOpenRepeatedNameDialog(true)
                    }
                } else {
                    console.log('Comensal existente')
                    console.log('tableCode: ', tableCode)
                    setCookie("customerName", name, {maxAge:60*60*5})
                    setCookie("tableCode", tableCode, {maxAge:60*60*5})
                    goToCategories()
                }
            } else { // Nuevo comensal
                console.log('Nuevo comensal')
                console.log('tableCode: ', tableCode)
                setCookie("customerName", name, {maxAge:60*60*5})
                setCookie("tableCode", tableCode, {maxAge:60*60*5})
                goToCategories()
            }
        }
    }

    return (<>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <NameInputMain onClick={onEnterName}/>
            <MessageDialog
                open={openRepeatedNameDialog}
                title='Nombre repetido'
                onSubmit={() => setOpenRepeatedNameDialog(false)}
                submitButtonText={"Aceptar"}
                cancelButtonVisible={false}
                description={'El nombre ingresado ya está en uso en esta mesa. Por favor, cambialo agregando tu apellido, o colocando o agregando algún número o letra'}/>

            <MessageDialog
                open={openEmptyNameDialog}
                title='Ingrese un nombre'
                onSubmit={() => setOpenEmptyNameDialog(false)}
                cancelButtonVisible={false}
                submitButtonText={"Aceptar"}
                description={'Debe ingresar un nombre para poder realizar una orden'}/>
        </main>
    </>)
}

