import Head from 'next/head'
import {useState, useEffect} from 'react';
import { useRouter } from 'next/router'
import { NameInputMain } from '@/Customer/NameInput/NameInputMain'
import { postCustomer } from '@/requests'
import {MessageDialog} from '@/Common/MessageDialog'
import {deleteCookie, getCookie, hasCookie, setCookie} from "cookies-next";
import { getTableOrders, tableExistsByTableCode } from '@/requests';

export default function StartPage() {
    const router = useRouter()
    const [tableCode, setTableCode] = useState('')
    const [openMessageDialog, setOpenMessageDialog] = useState(false)
    const [titleMessageDialog, setTitleMessageDialog] = useState('')
    const [descriptionMessageDialog, setDescriptionMessageDialog] = useState('')
    const [actionMessageDialog, setActionMessageDialog] = useState('')
    
    useEffect(() => {
        console.log(' ')
        console.log('Start useEffect')
        initialize()
    }, [])

    const goToBase = () => {
        router.replace({pathname:"/"})
    }

    const submitMessageDialog = () => {
        if(actionMessageDialog === 'repeated-name' || actionMessageDialog === 'empty-name'){
            setOpenMessageDialog(false)
        } else if(actionMessageDialog === 'table-not-exists'){
            setOpenMessageDialog(false)
            goToBase()
        }
    }
    
    const initialize = () => {
        console.log(' ')
        console.log('Home initialize')
        let hasTableCodeCookie = hasCookie("tableCode")
        console.log('hasTableCodeCookie: ', hasTableCodeCookie)

        if(hasTableCodeCookie){
            let tableCode = getCookie("tableCode")
            console.log('tableCode: ', tableCode)
            if(tableCode !== ''){
                setTableCode(tableCode)
                return true
            }
        }
        goToBase()
    }

    const goToCategories = () => {
        router.replace({
            pathname: "/menucategories",
        })
    }

    const onEnterName = async (name) => {
        console.log(' ')
        console.log('Start onEnterName(name)')
        console.log('name: ', name)
        if(name === ''){
            setOpenMessageDialog(true)
            setTitleMessageDialog('Nombre vacío')
            setDescriptionMessageDialog('Debe ingresar un nombre antes de entrar')
            setActionMessageDialog('emtpy-name')
        } else {
            const result = await postCustomer(name, tableCode)
            console.log('result: ', result)
            if(result === 'table-not-exists'){
                setCookie('tableCode', '', {maxAge:60*60*5})
                setOpenMessageDialog(true)
                setTitleMessageDialog('Mesa no reconocida')
                setDescriptionMessageDialog('El sistema no pudo reconocer la mesa. Por favor, vuelva a escanear el código QR')
                setActionMessageDialog('table-not-exists')
            } else if(result === 'customer-exists'){
                let hasCustomerNameCookie = hasCookie('customerName')
                console.log('hasCustomerNameCookie: ', hasCustomerNameCookie)
                if(hasCustomerNameCookie){
                    let customerName = getCookie('customerName')
                    if(customerName === name){
                        goToCategories()
                    } else {
                        setOpenMessageDialog(true)
                        setTitleMessageDialog('Nombre repetido')
                        setDescriptionMessageDialog('El nombre ingresado ya está en uso en esta mesa. Por favor, cambialo agregando tu apellido, o colocando o agregando algún número o letra')
                        setActionMessageDialog('repeated-name')
                    }
                } else {
                    console.log('Comensal existente')
                    console.log('tableCode: ', tableCode)
                    setCookie("customerName", name, {maxAge:60*60*5})
                    setCookie("tableCode", tableCode, {maxAge:60*60*5})
                    goToCategories()
                }
            } else { // Nuevo comensal
                console.log('Nuevo comensal')
                console.log('tableCode: ', tableCode)
                setCookie("customerName", name, {maxAge:60*60*5})
                setCookie("tableCode", tableCode, {maxAge:60*60*5})
                goToCategories()
            }
        }
    }

    return (<>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <NameInputMain onClick={onEnterName}/>
            <MessageDialog 
                open={openMessageDialog}
                submitButtonText={"Aceptar"}
                title={titleMessageDialog}
                cancelButtonVisible={false}
                onSubmit={submitMessageDialog}
                description={descriptionMessageDialog}
                onClose={() => setOpenMessageDialog(false)}/>
        </main>
    </>)
}

