import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/router'
import {useEffect} from 'react'
import {Layout} from "@/Restaurant/Layout/Layout";
import {FoodMenu} from "@/Restaurant/FoodMenu/FoodMenu";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const router = useRouter()

    useEffect(() => {
        if (router.asPath === '/') {
            router.replace('/orders');
        }
    }, []);

    return (<>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
            <Layout
                // onTables={}
                // onUsers={}
                // onOrders={}
                // onFoodMenu={}
            >
                <FoodMenu>

                </FoodMenu>

            </Layout>
        </main>




        {/*<main className={styles.main}>*/}
        {/*    <div className={styles.description}>*/}
        {/*    </div>*/}
        {/*</main>*/}
    </>)
}
